# Generated by Django 6.0.2 on 2026-03-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('icon_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Subject categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='lesson',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='subject',
            name='seo_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subject',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page view'), ('lesson_open', 'Lesson open'), ('lesson_play', 'Lesson play'), ('search', 'Search'), ('click', 'Click'), ('contact_submit', 'Contact submit')], default='page_view', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='application.subjectcategory'),
        ),
    ]
